### ISSUE TITLE
加入文档汉化

### ISSUE THREAD

**Issue by hihibaibai** [GamemakerChina/gamemakerchina.github.io#1]
**用户名：** hihibaibai
**相关项目：** GMS2 文档汉化

**Comment by LiarOnce** [comment]
请问你是否可以提供一下联系方式？我们需要考察一下翻译水平。

**Comment by hihibaibai** [comment]
979597463
这是我的qq号，能够联系上我的。





------------------ Original message ------------------
From: "Mark Shi"; 
Sendtime: Wednesday, Jul 10, 2019 12:52 PM
To: "GamemakerChina/gamemakerchina.github.io"; 
Cc: "滑稽"<979597463@qq.com>; "Author"; 
Subject: Re: [GamemakerChina/gamemakerchina.github.io] 加入文档汉化 (#1)




请问你是否可以提供一下联系方式？

**Comment by LiarOnce** [comment]
已通过！
CAT配置文档：https://github.com/GamemakerChina/GMS2_manual_en2ch/wiki/translation-issues

如果不清楚Git或TortoiseGit的话可以使用GitHub Desktop或者SourceTree代替

如果有翻译语法等问题可以在这里提出：https://github.com/GamemakerChina/GMS2_manual_en2ch/issues
